DROP TABLE IF EXISTS adr_form;
CREATE TABLE adr_form (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  institution_name varchar(50) DEFAULT NULL,
  institution_code int(11) DEFAULT NULL,
  address varchar(50) DEFAULT NULL,
  contact varchar(50) DEFAULT NULL,
  patient_name varchar(100) DEFAULT NULL,
  ip_no varchar(50) NOT NULL,
  dob date DEFAULT NULL,
  patient_address varchar(50) DEFAULT NULL,
  ward_clinic varchar(50) DEFAULT NULL,
  gender varchar(10) DEFAULT NULL,
  is_alergy tinyint(4) DEFAULT NULL,
  alergy_desc varchar(50) DEFAULT NULL,
  is_pregnant tinyint(4) DEFAULT NULL,
  weight varchar(5) DEFAULT NULL,
  height varchar(5) DEFAULT NULL,
  diagnosis varchar(100) DEFAULT NULL,
  reaction_description text,
  severity varchar(30) DEFAULT NULL,
  action_taken varchar(30) DEFAULT NULL,
  outcome varchar(30) DEFAULT NULL,
  reaction_casualty int(11) DEFAULT NULL,
  other_comment int(11) DEFAULT NULL,
  reporting_officer varchar(3) DEFAULT NULL,
  reporting_date varchar(10) DEFAULT NULL,
  email_address varchar(100) DEFAULT NULL,
  office_phone varchar(20) DEFAULT NULL,
  designation varchar(20) DEFAULT NULL,
  signature varchar(50) DEFAULT NULL,
  datecreated datetime NULL DEFAULT current_timestamp,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1//