REPLACE INTO `sync_regimen` (`id`, `name`, `code`, `old_code`, `description`, `category_id`) VALUES
(1, 'AZT + 3TC + NVP', 'AF1A', '', 'Zidovudine + Lamivudine + Nevirapine', 4),
(2, 'AZT + 3TC + EFV', 'AF1B', '', 'Zidovudine + Lamivudine + Efavirenz', 4),
(3, 'TDF + 3TC + NVP', 'AF2A', '', 'Tenofovir + Lamivudine + Nevirapine', 4),
(4, 'TDF + 3TC + EFV', 'AF2B', '', 'Tenofovir + Lamivudine + Efavirenz', 4),
(5, 'd4T + 3TC + NVP', 'AF3A', '', 'Stavudine + Lamivudine + Nevirapine', 4),
(6, 'd4T + 3TC + EFV', 'AF3B', '', 'Stavudine + Lamivudine + Efavirenz', 4),
(7, 'AZT + 3TC + LPV/r', 'AS1A', '', 'Zidovudine + Lamivudine + Lopinavir/Ritonavir', 5),
(10, 'TDF + 3TC + LPV/r', 'AS2A', '', 'Tenofovir + Lamivudine + Lopinavir/Ritonavir', 5),
(27, 'AZT 300mg BD (from week 14 to Delivery); then NVP 200mg stat + AZT 600mg stat (or 300mg BD) + 3TC 150mg BD during labour; then 1 tab of AZT/3TC 300mg/150mg BD for ONE week post-partum', 'PM1', '', 'PMTCT for the mother: Zidovudine 300mg BD (from week 14 to Delivery); then Nevirapine 200mg stat + Zidovudine 600mg stat (or 300mg BD) + Lamivudine 150mg BD during labour; then 1 tab of Zidovudine/Lamivudine 300mg/150mg BD for ONE week post-partum', 10),
(29, 'PMTCT HAART: AZT + 3TC + NVP', 'PM3', '', 'PMTCT HAART for the Mother: Zidovudine + Lamivudine + Nevirapine', 10),
(30, 'PMTCT HAART: AZT + 3TC + EFV', 'PM4', '', 'PMTCT HAART for the Mother: Zidovudine + Lamivudine + Efavirenz', 10),
(31, 'PMTCT HAART: AZT + 3TC + LPV/r', 'PM5', '', 'PMTCT HAART for the Mother: Zidovudine + Lamivudine + Lopinavir/Ritonavir', 10),
(35, 'NVP OD up to 6 weeks of age for: (i) Infants born of mothers on HAART (Breastfeeding or not); (ii) ALL Non-Breastfeeding infants born of mothers not on HAART', 'PC1', '', 'PMTCT for the Infant: Nevirapine syrup OD from Birth up to 6 weeks of age for: (i) Infants born of mothers on HAART (Breastfeeding or not); (ii) ALL Non-Breastfeeding infants born of mothers not on HAART', 11),
(36, 'NVP OD for Breastfeeding Infants until 1 week after complete cessation of Breastfeeding ', 'PC2', '', 'PMTCT for the Infant: Nevirapine syrup OD from Birth up to until 1 week after complete cessation of Breastfeeding (for Breastfeeding Infants)', 11),
(58, 'AZT + 3TC + NVP', 'CF1A', '', 'Zidovudine + Lamivudine + Nevirapine', 7),
(61, 'ABC + 3TC + NVP', 'CF2A', '', 'Abacavir + Lamivudine + Nevirapine', 7),
(62, 'ABC + 3TC + EFV', 'CF2B', '', 'Abacavir + Lamivudine + Efavirenz', 7),
(65, 'AZT + 3TC + EFV', 'CF1B', '', 'Zidovudine + Lamivudine + Efavirenz', 7),
(70, 'AZT + 3TC + LPV/r', 'CS1A', '', 'Zidovudine + Lamivudine + Lopinavir/Ritonavir ', 8),
(71, 'ABC + 3TC + LPV/r', 'CS2A', '', 'Abacavir + Lamivudine + Lopinavir/Ritonavir', 8),
(73, 'TDF + 3TC + LPV/r', 'CF4C', '', 'Tenofovir + Lamivudine + Lopinavir/Ritonavir', 9),
(76, 'TDF + 3TC + NVP', 'CF4A', '', 'Tenofovir + Lamivudine + Nevirapine', 9),
(119, 'AZT + 3TC + LPV/r', 'CF1C', '', 'Zidovudine + Lamivudine + Lopinavir/Ritonavir ', 7),
(121, 'AZT + 3TC + ATV/r', 'AS1B', '', 'Zidovudine + Lamivudine + Atazanavir/Ritonavir', 5),
(122, 'TDF + 3TC + ATV/r', 'AS2C', '', 'Tenofovir + Lamivudine + Atazanavir/Ritonavir', 5),
(125, 'ABC + 3TC + LPV/r', 'CF2D', '', 'Abacavir + Lamivudine + Lopinavir/Ritonavir ', 7),
(167, 'ABC + 3TC + NVP', 'AF4A', '', 'Abacavir + Lamivudine + Nevirapine', 4),
(168, 'ABC + 3TC + EFV', 'AF4B', '', 'Abacavir + Lamivudine + Efavirenz', 4),
(169, 'All other 1st line Adult regimens', 'AF5X', '', 'Total of ALL OTHER Adult patients on 1st line regimens not listed above (coded and uncoded)', 4),
(174, 'ABC + 3TC + LPV/r', 'AS5A', '', 'Abacavir + Lamivudine + Lopinavir/Ritonavir', 5),
(175, 'ABC + 3TC + ATV/r', 'AS5B', '', 'Abacavir + Lamivudine + Atazanavir/Ritonavir', 5),
(176, 'All other 2nd line Adult regimens', 'AS6X', '', 'Total of ALL OTHER Adult patients on 2nd line regimens not listed above (coded and uncoded regimens)', 5),
(177, 'RAL + 3TC + DRV + RTV', 'AT1A', '', 'Raltegravir + Lamivudine + Darunavir + Ritonavir', 17),
(178, 'RAL + 3TC + DRV + RTV + AZT', 'AT1B', '', 'Raltegravir + Lamivudine + Darunavir + Ritonavir + Zidovudine', 17),
(179, 'RAL + 3TC + DRV + RTV + TDF', 'AT1C', '', 'Raltegravir + Lamivudine + Darunavir + Ritonavir + Tenofovir', 17),
(180, 'ETV + 3TC + DRV + RTV', 'AT2A', '', 'Etravirine + Lamivudine + Darunavir + Ritonavir', 17),
(181, 'All other 3rd line Adult regimens', 'AT2X', '', 'Total of ALL OTHER Adult patients on 3rd line regimens not listed above (coded and uncoded regimens)', 17),
(185, 'AZT + 3TC + ATV/r', 'CF1D', '', 'Zidovudine + Lamivudine + Atazanavir/Ritonavir ', 7),
(189, 'ABC + 3TC + ATV/r', 'CF2E', '', 'Abacavir + Lamivudine + Atazanavir/Ritonavir', 7),
(190, 'd4T + 3TC + NVP for children weighing >= 25kg', 'CF3A', '', 'Stavudine + Lamivudine + Nevirapine', 7),
(191, 'd4T + 3TC + EFV for children weighing >= 25kg', 'CF3B', '', 'Stavudine + Lamivudine + Efavirenz', 7),
(193, 'TDF + 3TC + EFV', 'CF4B', '', 'Tenofovir + Lamivudine + Efavirenz', 9),
(195, 'TDF + 3TC + ATV/r', 'CF4D', '', 'Tenofovir + Lamivudine + Atazanavir/Ritonavir', 9),
(196, 'All other 1st line Paediatric regimens', 'CF5X', '', 'Total of ALL OTHER Paediatric patients on 1st line regimens not listed above (coded and uncoded regimens)', 9),
(198, 'AZT + 3TC + ATV/r', 'CS1B', '', 'Zidovudine + Lamivudine + Atazanavir/Ritonavir ', 8),
(200, 'ABC + 3TC + ATV/r', 'CS2C', '', 'Abacavir + Lamivudine + Atazanavir/Ritonavir', 8),
(201, 'All other 2nd line Paediatric regimens', 'CS4X', '', 'Total of ALL OTHER Paediatric patients on 2nd line regimens not listed above (coded and uncoded regimens)', 8),
(202, 'RAL + 3TC + DRV + RTV', 'CT1A', '', 'Raltegravir + Lamivudine + Darunavir + Ritonavir', 18),
(203, 'RAL + 3TC + DRV + RTV + AZT', 'CT1B', '', 'Raltegravir + Lamivudine + Darunavir + Ritonavir + Zidovudine', 18),
(204, 'RAL + 3TC + DRV + RTV + ABC', 'CT1C', '', 'Raltegravir + Lamivudine + Darunavir + Ritonavir + Abacavir', 18),
(205, 'ETV + 3TC + DRV + RTV', 'CT2A', '', 'Etravirine + Lamivudine + Darunavir + Ritonavir', 18),
(206, 'All other 3rd line Paediatric regimens', 'CT3X', '', 'Total of ALL OTHER Paed patients on 3rd line regimens not listed above (coded and uncoded regimens)', 18),
(208, 'NVP 200mg stat + AZT 600mg stat (or 300mg BD) + 3TC 150mg BD during labour; then 1 tab of AZT/3TC 300mg/150mg BD for one week post-partum', 'PM2', '', 'PMTCT for the mother: Nevirapine 200mg stat + Zidovudine 600mg stat (or 300mg BD) + Lamivudine 150mg BD during labour; then 1 tab of Zidovudine/Lamivudine 300mg/150mg BD for ONE week post-partum (for Women coming for first time when in Labour)', 10),
(212, 'PMTCT HAART: TDF + 3TC + NVP', 'PM6', '', 'PMTCT HAART for the Mother: Tenofovir + Lamivudine + Nevirapine', 10),
(213, 'PMTCT HAART: TDF + 3TC + LPV/r', 'PM7', '', 'PMTCT HAART for the Mother: Tenofovir + Lamivudine + Lopinavir/Ritonavir   [For use by Pregnant women with less than 2 years NVP exposure and who never received the 3TC tail]', 10),
(214, 'PMTCT HAART: TDF + 3TC + EFV', 'PM9', '', 'PMTCT HAART for the Mother: Tenofovir + Lamivudine + Efavirenz', 10),
(215, 'PMTCT HAART: AZT + 3TC + ATV/r', 'PM10', '', 'PMTCT HAART for the Mother: Zidovudine + Lamivudine + Atazanavir/Ritonavir', 10),
(216, 'PMTCT HAART: TDF + 3TC + ATV/r', 'PM11', '', 'PMTCT HAART for the Mother: Tenofovir + Lamivudine + Atazanavir/Ritonavir', 10),
(217, 'All other PMTCT regimens for Women', 'PM1X', '', 'Total of ALL other PMTCT regimens for Women not listed above (coded and uncoded regimens)', 10),
(220, 'AZT Liquid BD for 6 weeks ', 'PC4', '', 'PMTCT for the Infant: Zidovudine syrup BD for 6 weeks (Alternative for infants on TB treatment or NVP toxicity)', 11),
(221, '3TC Liquid BD', 'PC5', '', 'PMTCT for the Infant: Lamivudine syrup BD Infant Lamivudine prophylaxis for infants who cannot take NVP due to severe NVP toxicity (grade 3 or 4)/or if baby is on TB treatment with rifampicin containing regimen', 11),
(222, 'NVP Liquid OD for 12 weeks ', 'PC6', '', 'PMTCT for the Infant: Nevirapine syrup OD for 12 weeks Nevirapine prophylaxis for infants whose mothers who start ART after 38 weeks gestation, delivery or immediate postpartum', 11),
(223, 'All other PMTCT regimens for Infants', 'PC1X', '', 'Total of ALL other PMTCT regimens for Infants not listed above (coded and uncoded regimens)', 11),
(224, 'AZT + 3TC + LPV/r (Adult PEP)', 'PA1B', '', 'Zidovudine + Lamivudine + Lopinavir/Ritonavir ', 12),
(225, 'AZT + 3TC + ATV/r (Adult PEP)', 'PA1C', '', 'Zidovudine + Lamivudine + Atazanavir/Ritonavir', 12),
(226, 'TDF + 3TC + LPV/r (Adult PEP)', 'PA3B', '', 'Tenofovir + Lamivudine + Lopinavir/Ritonavir', 12),
(227, 'TDF + 3TC + ATV/r (Adult PEP)', 'PA3C', '', 'Tenofovir + Lamivudine + Atazanavir/Ritonavir', 12),
(228, 'All other PEP regimens for Adults', 'PA4X', '', 'Total of ALL OTHER Adult PEP patients not listed above', 12),
(229, 'AZT + 3TC + LPV/r (Paed PEP)', 'PC1A', '', 'Zidovudine + Lamivudine + Lopinavir/Ritonavir', 13),
(230, 'ABC + 3TC + LPV/r (Paed PEP)', 'PC3A', '', 'Abacavir + Lamivudine + Lopinavir/Ritonavir', 13),
(231, 'All other PEP regimens for Children', 'PC4X', '', 'Total of ALL OTHER Paed PEP patients not listed above', 13),
(232, 'Adult patients (=>15 Yrs) on Cotrimoxazole prophylaxis ', 'OI1A', '', 'Total number of Adult Patients / Clients (ART plus Non-ART) on Cotrimoxazole prophylaxis', 19),
(233, 'Paediatric patients (<15 Yrs) on Cotrimoxazole prophylaxis ', 'OI1C', '', 'Total number of Paed Patients / Clients (ART plus Non-ART) on Cotrimoxazole prophylaxis', 19),
(234, 'Adult patients (=>15 Yrs) on Dapsone prophylaxis ', 'OI2A', '', 'Total number of Adult Patients / Clients (ART plus Non-ART) on Dapsone prophylaxis', 19),
(235, 'Paediatric patients (<15 Yrs) on Dapsone prophylaxis ', 'OI2C', '', 'Total number of Paed Patients / Clients (ART plus Non-ART) on Dapsone prophylaxis', 19),
(236, 'Adult patients (=>15 Yrs) on Isoniazid prophylaxis ', 'OI4A', '', 'Total number of Adult Patients / Clients (ART plus Non-ART) on Isoniazid prophylaxis', 20),
(237, 'Paediatric patients (<15 Yrs) on Isoniazid prophylaxis ', 'OI4C', '', 'Total number of Paed Patients / Clients (ART plus Non-ART) on Isoniazid prophylaxis', 20),
(238, 'Adult patients on Diflucan (For Diflucan Donation Program ONLY)', 'OI3A', '', 'Total number of Adult Patients / Clients on Diflucan (For Diflucan Donation Program ONLY)2', 21),
(239, 'Paed patients on Diflucan (For Diflucan Donation Program ONLY)', 'OI3C', '', 'Total number of Paed Patients / Clients on Diflucan (For Diflucan Donation Program ONLY)3', 21),
(240, 'New patients with CM on Diflucan (For Diflucan Donation Program ONLY)', 'CM3N', '', 'Total number of New Patients / Clients on Diflucan - disaggregated by Cryptococcal meningitis (CM)', 21),
(241, 'Revisit patients with CM on Diflucan (For Diflucan Donation Program ONLY)', 'CM3R', '', 'Total number of Revisit Patients / Clients on Diflucan - disaggregated by Cryptococcal meningitis (CM)', 21),
(242, 'New patients with OC on Diflucan (For Diflucan Donation Program ONLY)', 'OC3N', '', 'Total number of New Patients / Clients on Diflucan - disaggregated by Oesophageal candidiasis (OC)', 21),
(243, 'Revisit patients with OC on Diflucan (For Diflucan Donation Program ONLY)', 'OC3R', '', 'Total number of Revisit Patients / Clients on Diflucan - disaggregated by Oesophageal candidiasis (OC)', 21)//

REPLACE INTO `sync_regimen` (`id`, `name`, `code`, `old_code`, `description`, `category_id`) VALUES
(270, 'AZT + 3TC + DTG', 'AF1D', '', '', 4),
(271, 'TDF + 3TC + ATV/r', 'AF2D', '', '', 4),
(272, 'TDF + 3TC + DTG', 'AF2E', '', '', 4),
(273, 'TDF + 3TC + LPV/r (1L Adults <40kg)', 'AF2F', '', '', 4),
(274, 'TDF + 3TC + RAL (PWIDs intoIerant to ATV)', 'AF2G', '', '', 4),
(275, 'TDF + FTC + ATV/r', 'AF2H', '', '', 4),
(276, 'ABC + 3TC + DTG', 'AF4C', '', '', 4),
(277, 'RAL + DRV + RTV + ETV + other backbone ARVs', 'AT1D', '', '', 17),
(278, 'RAL + ETV + other backbone ARVs', 'AT1E', '', '', 17),
(279, 'RAL + DRV + RTV + other backbone ARVs', 'AT1F', '', '', 17),
(280, 'RAL + other backbone ARVs (2nd Line patients failing treatment)', 'AT1G', '', '', 17),
(281, 'ETV + other backbone ARVs', 'AT2B', '', '', 17),
(282, 'ETV + DRV + RTV + other backbone ARVs', 'AT2C', '', '', 17),
(283, 'DRV + RTV + other backbone ARVs', 'AT3A', '', '', 17),
(284, 'DTG + DRV + RTV + ETV + other backbone ARVs', 'AT4A', '', '', 17),
(285, 'DTG + ETV + other backbone ARVs', 'AT4B', '', '', 17),
(286, 'DTG + DRV + RTV + other backbone ARVs', 'AT4C', '', '', 17),
(287, 'DTG + other backbone ARVs (2nd Line patients failing treatment)', 'AT4D', '', '', 17),
(288, 'AZT + 3TC + RAL', 'CF1E', '', '', 7),
(289, 'ABC + 3TC + RAL', 'CF2F', '', '', 7),
(290, 'TDF + 3TC + NVP (children > 35kg)', 'CF4A', '', '', 7),
(291, 'TDF + 3TC + EFV', 'CF4B', '', '', 7),
(292, 'TDF + 3TC + LPV/r', 'CF4C', '', '', 7),
(293, 'TDF + 3TC + ATV/r', 'CF4D', '', '', 7),
(294, 'RAL + DRV + RTV + ETV + other backbone ARVs', 'CT1D', '', '', 18),
(295, 'RAL + ETV + other backbone ARVs', 'CT1E', '', '', 18),
(296, 'RAL + DRV + RTV + other backbone ARVs', 'CT1F', '', '', 18),
(297, 'RAL + other backbone ARVs', 'CT1G', '', '', 18),
(298, 'ETV + other backbone ARVs', 'CT2B', '', '', 18),
(299, 'ETV + DRV + RTV + other backbone ARVs', 'CT2C', '', '', 18),
(300, 'DRV + RTV + other backbone ARVs', 'CT3A', '', '', 18),
(301, 'DTG + DRV + RTV + ETV + other backbone ARVs', 'CT4A', '', '', 18),
(302, 'DTG + ETV + other backbone ARVs', 'CT4B', '', '', 18),
(303, 'DTG + DRV + RTV + other backbone ARVs', 'CT4C', '', '', 18),
(304, 'DTG + other backbone ARVs', 'CT4D', '', '', 18),
(305, 'AZT liquid BID + NVP liquid OD for 6 weeks then NVP liquid OD for 6 weeks', 'PC7', '', '', 11),
(306, 'AZT liquid BID + NVP liquid OD for 6 weeks then NVP liquid OD until 6 weeks after complete cessation of Breastfeeding (mother NOT on ART)', 'PC8', '', '', 11),
(307, 'AZT liquid BID for 12 weeks', 'PC9', '', '', 11),
(308, 'TDF + FTC (PrEP)', 'PRP1A', '', '', 22),
(309, 'TDF + 3TC (PrEP)', 'PRP1B', '', '', 22),
(310, 'TDF (PrEP)', 'PRP1C', '', '', 22),
(311, 'TDF + 3TC (HIV-ve HepB patients)', 'HPB1A', '', '', 23),
(312, 'TDF + FTC (HIV-ve HepB patients)', 'HPB1B', '', '', 23),
(313, 'Adult patients (=>15 Yrs) newly started on IPT in the month', 'OI4AN', '', '', 24),
(314, 'Paed patients (<15 Yrs) newly started on IPT in the month', 'OI4CN', '', '', 24),
(315, 'Adult patients (=>15 Yrs) on Fluconazole in the month', 'OI5A', '', '', 24),
(316, 'Paed patients (<15 Yrs) on Fluconazole in the month', 'OI5C', '', '', 24)//