CREATE TABLE IF NOT EXISTS `sync_facility` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `code` varchar(15) DEFAULT NULL,
  `category` varchar(15) DEFAULT NULL,
  `sponsors` varchar(255) DEFAULT NULL,
  `services` varchar(255) DEFAULT NULL,
  `manager_id` int(11) UNSIGNED DEFAULT NULL,
  `district_id` int(11) UNSIGNED NOT NULL,
  `address_id` int(11) UNSIGNED DEFAULT NULL,
  `parent_id` int(11) UNSIGNED DEFAULT NULL,
  `ordering` tinyint(1) NOT NULL DEFAULT '1',
  `affiliation` varchar(255) DEFAULT NULL,
  `service_point` tinyint(1) NOT NULL DEFAULT '1',
  `county_id` int(11) UNSIGNED DEFAULT NULL,
  `hcsm_id` int(11) UNSIGNED DEFAULT NULL,
  `keph_level` varchar(25) DEFAULT 'Not Classified',
  `location` varchar(255) DEFAULT NULL,
  `affiliate_organization_id` int(11) UNSIGNED DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8//