DROP TABLE IF EXISTS pv_countries//
CREATE TABLE pv_countries (
  id int(11) NOT NULL AUTO_INCREMENT,
  code char(2) CHARACTER SET latin1 DEFAULT '',
  name tinytext CHARACTER SET latin1,
  name_fr tinytext CHARACTER SET latin1,
  created datetime DEFAULT NULL,
  modified datetime DEFAULT NULL,
  PRIMARY KEY (id)
)//

INSERT INTO pv_countries (id, code, name, name_fr, created, modified) VALUES
(1,	'AD',	'Andorra',	'Andorre',	NULL,	NULL),
(2,	'AE',	'United Arab Emirates',	'Émirats arabes unis',	NULL,	NULL),
(3,	'AF',	'Afghanistan',	'Afghanistan',	NULL,	NULL),
(4,	'AG',	'Antigua and Barbuda',	'Antigua-et-Barbuda',	NULL,	NULL),
(5,	'AI',	'Anguilla',	'Anguilla',	NULL,	NULL),
(6,	'AL',	'Albania',	'Albanie',	NULL,	NULL),
(7,	'AM',	'Armenia',	'Arménie',	NULL,	NULL),
(8,	'AO',	'Angola',	'Angola',	NULL,	'2012-07-09 14:58:07'),
(9,	'AQ',	'Antarctica',	'Antarctique',	NULL,	NULL),
(10,	'AR',	'Argentina',	'Argentine',	NULL,	NULL),
(11,	'AS',	'American Samoa',	'Samoa américaine',	NULL,	NULL),
(12,	'AT',	'Austria',	'Autriche',	NULL,	NULL),
(13,	'AU',	'Australia',	'Australie',	NULL,	NULL),
(14,	'AW',	'Aruba',	'Aruba',	NULL,	NULL),
(16,	'AZ',	'Azerbaijan',	'Azerbaïdjan',	NULL,	NULL),
(17,	'BA',	'Bosnia and Herzegovina',	'Bosnie-Herzégovine',	NULL,	NULL),
(18,	'BB',	'Barbados',	'Barbade',	NULL,	NULL),
(19,	'BD',	'Bangladesh',	'Bangladesh',	NULL,	NULL),
(20,	'BE',	'Belgium',	'Belgique',	NULL,	NULL),
(21,	'BF',	'Burkina Faso',	'Burkina Faso',	NULL,	NULL),
(22,	'BG',	'Bulgaria',	'Bulgarie',	NULL,	NULL),
(23,	'BH',	'Bahrain',	'Bahreïn',	NULL,	NULL),
(24,	'BI',	'Burundi',	'Burundi',	NULL,	NULL),
(25,	'BJ',	'Benin',	'Bénin',	NULL,	NULL),
(26,	'BL',	'Saint Barthélemy',	'Saint-Barthélemy',	NULL,	NULL),
(27,	'BM',	'Bermuda',	'Bermudes',	NULL,	NULL),
(28,	'BN',	'Brunei Darussalam',	'Brunei Darussalam',	NULL,	NULL),
(29,	'BO',	'Bolivia',	'Bolivie',	NULL,	NULL),
(30,	'BQ',	'Caribbean Netherlands ',	'Pays-Bas caribéens',	NULL,	NULL),
(31,	'BR',	'Brazil',	'Brésil',	NULL,	NULL),
(32,	'BS',	'Bahamas',	'Bahamas',	NULL,	NULL),
(33,	'BT',	'Bhutan',	'Bhoutan',	NULL,	NULL),
(34,	'BV',	'Bouvet Island',	'Île Bouvet',	NULL,	NULL),
(35,	'BW',	'Botswana',	'Botswana',	NULL,	NULL),
(36,	'BY',	'Belarus',	'Bélarus',	NULL,	NULL),
(37,	'BZ',	'Belize',	'Belize',	NULL,	NULL),
(38,	'CA',	'Canada',	'Canada',	NULL,	NULL),
(39,	'CC',	'Cocos (Keeling) Islands',	'Îles Cocos (Keeling)',	NULL,	NULL),
(40,	'CD',	'Congo, Democratic Republic of',	'Congo, République démocratique du',	NULL,	NULL),
(41,	'CF',	'Central African Republic',	'République centrafricaine',	NULL,	NULL),
(42,	'CG',	'Congo',	'Congo',	NULL,	NULL),
(43,	'CH',	'Switzerland',	'Suisse',	NULL,	NULL),
(44,	'CI',	'Côte D’Ivoire',	'Côte d’Ivoire',	NULL,	NULL),
(45,	'CK',	'Cook Islands',	'Îles Cook',	NULL,	NULL),
(46,	'CL',	'Chile',	'Chili',	NULL,	NULL),
(47,	'CM',	'Cameroon',	'Cameroun',	NULL,	NULL),
(48,	'CN',	'China',	'Chine',	NULL,	NULL),
(49,	'CO',	'Colombia',	'Colombie',	NULL,	NULL),
(50,	'CR',	'Costa Rica',	'Costa Rica',	NULL,	NULL),
(51,	'CU',	'Cuba',	'Cuba',	NULL,	NULL),
(52,	'CV',	'Cape Verde',	'Cap-Vert',	NULL,	NULL),
(53,	'CW',	'Curaçao',	'Curaçao',	NULL,	NULL),
(54,	'CX',	'Christmas Island',	'Île Christmas',	NULL,	NULL),
(55,	'CY',	'Cyprus',	'Chypre',	NULL,	NULL),
(56,	'CZ',	'Czech Republic',	'République tchèque',	NULL,	NULL),
(57,	'DE',	'Germany',	'Allemagne',	NULL,	NULL),
(58,	'DJ',	'Djibouti',	'Djibouti',	NULL,	NULL),
(59,	'DK',	'Denmark',	'Danemark',	NULL,	NULL),
(60,	'DM',	'Dominica',	'Dominique',	NULL,	NULL),
(61,	'DO',	'Dominican Republic',	'République dominicaine',	NULL,	NULL),
(62,	'DZ',	'Algeria',	'Algérie',	NULL,	NULL),
(63,	'EC',	'Ecuador',	'Équateur',	NULL,	NULL),
(64,	'EE',	'Estonia',	'Estonie',	NULL,	NULL),
(65,	'EG',	'Egypt',	'Égypte',	NULL,	NULL),
(66,	'EH',	'Western Sahara',	'Sahara Occidental',	NULL,	NULL),
(67,	'ER',	'Eritrea',	'Érythrée',	NULL,	NULL),
(68,	'ES',	'Spain',	'Espagne',	NULL,	NULL),
(69,	'ET',	'Ethiopia',	'Éthiopie',	NULL,	NULL),
(70,	'FI',	'Finland',	'Finlande',	NULL,	NULL),
(71,	'FJ',	'Fiji',	'Fidji',	NULL,	NULL),
(72,	'FK',	'Falkland Islands',	'Îles Malouines',	NULL,	NULL),
(73,	'FM',	'Micronesia, Federated States of',	'Micronésie, États fédérés de',	NULL,	NULL),
(74,	'FO',	'Faroe Islands',	'Îles Féroé',	NULL,	NULL),
(75,	'FR',	'France',	'France',	NULL,	NULL),
(76,	'GA',	'Gabon',	'Gabon',	NULL,	NULL),
(77,	'GB',	'United Kingdom',	'Royaume-Uni',	NULL,	NULL),
(78,	'GD',	'Grenada',	'Grenade',	NULL,	NULL),
(79,	'GE',	'Georgia',	'Géorgie',	NULL,	NULL),
(80,	'GF',	'French Guiana',	'Guyane française',	NULL,	NULL),
(81,	'GG',	'Guernsey',	'Guernesey',	NULL,	NULL),
(82,	'GH',	'Ghana',	'Ghana',	NULL,	NULL),
(83,	'GI',	'Gibraltar',	'Gibraltar',	NULL,	NULL),
(84,	'GL',	'Greenland',	'Groenland',	NULL,	NULL),
(85,	'GM',	'Gambia',	'Gambie',	NULL,	NULL),
(86,	'GN',	'Guinea',	'Guinée',	NULL,	NULL),
(87,	'GP',	'Guadeloupe',	'Guadeloupe',	NULL,	NULL),
(88,	'GQ',	'Equatorial Guinea',	'Guinée équatoriale',	NULL,	NULL),
(89,	'GR',	'Greece',	'Grèce',	NULL,	NULL),
(90,	'GS',	'South Georgia and the South Sandwich Islands',	'Géorgie du Sud et les îles Sandwich du Sud',	NULL,	NULL),
(91,	'GT',	'Guatemala',	'Guatemala',	NULL,	NULL),
(92,	'GU',	'Guam',	'Guam',	NULL,	NULL),
(93,	'GW',	'Guinea-Bissau',	'Guinée-Bissau',	NULL,	NULL),
(94,	'GY',	'Guyana',	'Guyana',	NULL,	NULL),
(95,	'HK',	'Hong Kong',	'Hong Kong',	NULL,	NULL),
(96,	'HM',	'Heard and McDonald Islands',	'Îles Heard et McDonald',	NULL,	NULL),
(97,	'HN',	'Honduras',	'Honduras',	NULL,	NULL),
(98,	'HR',	'Croatia',	'Croatie',	NULL,	NULL),
(99,	'HT',	'Haiti',	'Haïti',	NULL,	NULL),
(100,	'HU',	'Hungary',	'Hongrie',	NULL,	NULL),
(101,	'ID',	'Indonesia',	'Indonésie',	NULL,	NULL),
(102,	'IE',	'Ireland',	'Irlande',	NULL,	NULL),
(103,	'IL',	'Israel',	'Israël',	NULL,	NULL),
(104,	'IM',	'Isle of Man',	'Île de Man',	NULL,	NULL),
(105,	'IN',	'India',	'Inde',	NULL,	NULL),
(106,	'IO',	'British Indian Ocean Territory',	'Territoire britannique de l\'océan Indien',	NULL,	NULL),
(107,	'IQ',	'Iraq',	'Irak',	NULL,	NULL),
(108,	'IR',	'Iran',	'Iran',	NULL,	NULL),
(109,	'IS',	'Iceland',	'Islande',	NULL,	NULL),
(110,	'IT',	'Italy',	'Italie',	NULL,	NULL),
(111,	'JE',	'Jersey',	'Jersey',	NULL,	NULL),
(112,	'JM',	'Jamaica',	'Jamaïque',	NULL,	NULL),
(113,	'JO',	'Jordan',	'Jordanie',	NULL,	NULL),
(114,	'JP',	'Japan',	'Japon',	NULL,	NULL),
(115,	'KE',	'Kenya',	'Kenya',	NULL,	NULL),
(116,	'KG',	'Kyrgyzstan',	'Kirghizistan',	NULL,	NULL),
(117,	'KH',	'Cambodia',	'Cambodge',	NULL,	NULL),
(118,	'KI',	'Kiribati',	'Kiribati',	NULL,	NULL),
(119,	'KM',	'Comoros',	'Comores',	NULL,	NULL),
(120,	'KN',	'Saint Kitts and Nevis',	'Saint-Kitts-et-Nevis',	NULL,	NULL),
(121,	'KP',	'North Korea',	'Corée du Nord',	NULL,	NULL),
(122,	'KR',	'South Korea',	'Corée du Sud',	NULL,	NULL),
(123,	'KW',	'Kuwait',	'Koweït',	NULL,	NULL),
(124,	'KY',	'Cayman Islands',	'Îles Caïmans',	NULL,	NULL),
(125,	'KZ',	'Kazakhstan',	'Kazakhstan',	NULL,	NULL),
(126,	'LA',	'Lao People’s Democratic Republic',	'Laos',	NULL,	NULL),
(127,	'LB',	'Lebanon',	'Liban',	NULL,	NULL),
(128,	'LC',	'Saint Lucia',	'Sainte-Lucie',	NULL,	NULL),
(129,	'LI',	'Liechtenstein',	'Liechtenstein',	NULL,	NULL),
(130,	'LK',	'Sri Lanka',	'Sri Lanka',	NULL,	NULL),
(131,	'LR',	'Liberia',	'Libéria',	NULL,	NULL),
(132,	'LS',	'Lesotho',	'Lesotho',	NULL,	NULL),
(133,	'LT',	'Lithuania',	'Lituanie',	NULL,	NULL),
(134,	'LU',	'Luxembourg',	'Luxembourg',	NULL,	NULL),
(135,	'LV',	'Latvia',	'Lettonie',	NULL,	NULL),
(136,	'LY',	'Libya',	'Libye',	NULL,	NULL),
(137,	'MA',	'Morocco',	'Maroc',	NULL,	NULL),
(138,	'MC',	'Monaco',	'Monaco',	NULL,	NULL),
(139,	'MD',	'Moldova',	'Moldavie',	NULL,	NULL),
(140,	'ME',	'Montenegro',	'Monténégro',	NULL,	NULL),
(141,	'MF',	'Saint-Martin (France)',	'Saint-Martin (France)',	NULL,	NULL),
(142,	'MG',	'Madagascar',	'Madagascar',	NULL,	NULL),
(143,	'MH',	'Marshall Islands',	'Îles Marshall',	NULL,	NULL),
(144,	'MK',	'Macedonia',	'Macédoine',	NULL,	NULL),
(145,	'ML',	'Mali',	'Mali',	NULL,	NULL),
(146,	'MM',	'Myanmar',	'Myanmar',	NULL,	NULL),
(147,	'MN',	'Mongolia',	'Mongolie',	NULL,	NULL),
(148,	'MO',	'Macau',	'Macao',	NULL,	NULL),
(149,	'MP',	'Northern Mariana Islands',	'Mariannes du Nord',	NULL,	'2012-07-09 14:14:26'),
(150,	'MQ',	'Martinique',	'Martinique',	NULL,	NULL),
(151,	'MR',	'Mauritania',	'Mauritanie',	NULL,	NULL),
(152,	'MS',	'Montserrat',	'Montserrat',	NULL,	NULL),
(153,	'MT',	'Malta',	'Malte',	NULL,	NULL),
(154,	'MU',	'Mauritius',	'Maurice',	NULL,	NULL),
(155,	'MV',	'Maldives',	'Maldives',	NULL,	NULL),
(156,	'MW',	'Malawi',	'Malawi',	NULL,	NULL),
(157,	'MX',	'Mexico',	'Mexique',	NULL,	NULL),
(158,	'MY',	'Malaysia',	'Malaisie',	NULL,	NULL),
(159,	'MZ',	'Mozambique',	'Mozambique',	NULL,	NULL),
(160,	'NA',	'Namibia',	'Namibie',	NULL,	NULL),
(161,	'NC',	'New Caledonia',	'Nouvelle-Calédonie',	NULL,	NULL),
(162,	'NE',	'Niger',	'Niger',	NULL,	NULL),
(163,	'NF',	'Norfolk Island',	'Île Norfolk',	NULL,	NULL),
(164,	'NG',	'Nigeria',	'Nigeria',	NULL,	NULL),
(165,	'NI',	'Nicaragua',	'Nicaragua',	NULL,	NULL),
(166,	'NL',	'The Netherlands',	'Pays-Bas',	NULL,	NULL),
(167,	'NO',	'Norway',	'Norvège',	NULL,	NULL),
(168,	'NP',	'Nepal',	'Népal',	NULL,	NULL),
(169,	'NR',	'Nauru',	'Nauru',	NULL,	NULL),
(170,	'NU',	'Niue',	'Niue',	NULL,	NULL),
(171,	'NZ',	'New Zealand',	'Nouvelle-Zélande',	NULL,	NULL),
(172,	'OM',	'Oman',	'Oman',	NULL,	NULL),
(173,	'PA',	'Panama',	'Panama',	NULL,	NULL),
(174,	'PE',	'Peru',	'Pérou',	NULL,	NULL),
(175,	'PF',	'French Polynesia',	'Polynésie française',	NULL,	NULL),
(176,	'PG',	'Papua New Guinea',	'Papouasie-Nouvelle-Guinée',	NULL,	NULL),
(177,	'PH',	'Philippines',	'Philippines',	NULL,	NULL),
(178,	'PK',	'Pakistan',	'Pakistan',	NULL,	NULL),
(179,	'PL',	'Poland',	'Pologne',	NULL,	NULL),
(180,	'PM',	'St. Pierre and Miquelon',	'Saint-Pierre-et-Miquelon',	NULL,	NULL),
(181,	'PN',	'Pitcairn',	'Pitcairn',	NULL,	NULL),
(182,	'PR',	'Puerto Rico',	'Puerto Rico',	NULL,	NULL),
(183,	'PS',	'Palestinian Territory, Occupied',	'Territoires palestiniens',	NULL,	NULL),
(184,	'PT',	'Portugal',	'Portugal',	NULL,	NULL),
(185,	'PW',	'Palau',	'Palau',	NULL,	NULL),
(186,	'PY',	'Paraguay',	'Paraguay',	NULL,	NULL),
(187,	'QA',	'Qatar',	'Qatar',	NULL,	NULL),
(188,	'RE',	'Reunion',	'Réunion',	NULL,	NULL),
(189,	'RO',	'Romania',	'Roumanie',	NULL,	NULL),
(190,	'RS',	'Serbia',	'Serbie',	NULL,	NULL),
(191,	'RU',	'Russian Federation',	'Russie',	NULL,	NULL),
(192,	'RW',	'Rwanda',	'Rwanda',	NULL,	NULL),
(193,	'SA',	'Saudi Arabia',	'Arabie saoudite',	NULL,	NULL),
(194,	'SB',	'Solomon Islands',	'Îles Salomon',	NULL,	NULL),
(195,	'SC',	'Seychelles',	'Seychelles',	NULL,	NULL),
(196,	'SD',	'Sudan',	'Soudan',	NULL,	NULL),
(197,	'SE',	'Sweden',	'Suède',	NULL,	NULL),
(198,	'SG',	'Singapore',	'Singapour',	NULL,	NULL),
(199,	'SH',	'Saint Helena',	'Sainte-Hélène',	NULL,	NULL),
(200,	'SI',	'Slovenia',	'Slovénie',	NULL,	NULL),
(201,	'SJ',	'Svalbard and Jan Mayen Islands',	'Svalbard et île de Jan Mayen',	NULL,	NULL),
(202,	'SK',	'Slovakia (Slovak Republic)',	'Slovaquie (République slovaque)',	NULL,	NULL),
(203,	'SL',	'Sierra Leone',	'Sierra Leone',	NULL,	NULL),
(204,	'SM',	'San Marino',	'Saint-Marin',	NULL,	NULL),
(205,	'SN',	'Senegal',	'Sénégal',	NULL,	NULL),
(206,	'SO',	'Somalia',	'Somalie',	NULL,	NULL),
(207,	'SR',	'Suriname',	'Suriname',	NULL,	NULL),
(208,	'SS',	'South Sudan',	'Soudan du Sud',	NULL,	NULL),
(209,	'ST',	'Sao Tome and Principe',	'Sao Tomé-et-Principe',	NULL,	NULL),
(210,	'SV',	'El Salvador',	'El Salvador',	NULL,	NULL),
(211,	'SX',	'Saint-Martin (Pays-Bas)',	'Sint Maarten ',	NULL,	NULL),
(212,	'SY',	'Syria',	'Syrie',	NULL,	NULL),
(213,	'SZ',	'Swaziland',	'Swaziland',	NULL,	NULL),
(214,	'TC',	'Turks and Caicos Islands',	'Îles Turks et Caicos',	NULL,	NULL),
(215,	'TD',	'Chad',	'Tchad',	NULL,	NULL),
(216,	'TF',	'French Southern Territories',	'Terres australes françaises',	NULL,	NULL),
(217,	'TG',	'Togo',	'Togo',	NULL,	NULL),
(218,	'TH',	'Thailand',	'Thaïlande',	NULL,	NULL),
(219,	'TJ',	'Tajikistan',	'Tadjikistan',	NULL,	NULL),
(220,	'TK',	'Tokelau',	'Tokelau',	NULL,	NULL),
(221,	'TL',	'Timor-Leste',	'Timor-Leste',	NULL,	NULL),
(222,	'TM',	'Turkmenistan',	'Turkménistan',	NULL,	NULL),
(223,	'TN',	'Tunisia',	'Tunisie',	NULL,	NULL),
(224,	'TO',	'Tonga',	'Tonga',	NULL,	NULL),
(225,	'TR',	'Turkey',	'Turquie',	NULL,	NULL),
(226,	'TT',	'Trinidad and Tobago',	'Trinité-et-Tobago',	NULL,	NULL),
(227,	'TV',	'Tuvalu',	'Tuvalu',	NULL,	NULL),
(228,	'TW',	'Taiwan',	'Taïwan',	NULL,	NULL),
(229,	'TZ',	'Tanzania',	'Tanzanie',	NULL,	NULL),
(230,	'UA',	'Ukraine',	'Ukraine',	NULL,	NULL),
(231,	'UG',	'Uganda',	'Ouganda',	NULL,	NULL),
(232,	'UM',	'United States Minor Outlying Islands',	'Îles mineures éloignées des États-Unis',	NULL,	NULL),
(233,	'US',	'United States',	'États-Unis',	NULL,	NULL),
(234,	'UY',	'Uruguay',	'Uruguay',	NULL,	NULL),
(235,	'UZ',	'Uzbekistan',	'Ouzbékistan',	NULL,	NULL),
(236,	'VA',	'Vatican',	'Vatican',	NULL,	NULL),
(237,	'VC',	'Saint Vincent and the Grenadines',	'Saint-Vincent-et-les-Grenadines',	NULL,	NULL),
(238,	'VE',	'Venezuela',	'Venezuela',	NULL,	NULL),
(239,	'VG',	'Virgin Islands (British)',	'Îles Vierges britanniques',	NULL,	NULL),
(240,	'VI',	'Virgin Islands (U.S.)',	'Îles Vierges américaines',	NULL,	NULL),
(241,	'VN',	'Vietnam',	'Vietnam',	NULL,	NULL),
(242,	'VU',	'Vanuatu',	'Vanuatu',	NULL,	NULL),
(243,	'WF',	'Wallis and Futuna Islands',	'Îles Wallis-et-Futuna',	NULL,	NULL),
(244,	'WS',	'Samoa',	'Samoa',	NULL,	NULL),
(245,	'YE',	'Yemen',	'Yémen',	NULL,	NULL),
(246,	'YT',	'Mayotte',	'Mayotte',	NULL,	NULL),
(247,	'ZA',	'South Africa',	'Afrique du Sud',	NULL,	NULL),
(248,	'ZM',	'Zambia',	'Zambie',	NULL,	NULL),
(249,	'ZW',	'Zimbabwe',	'Zimbabwe',	NULL,	NULL)//