DROP TABLE IF EXISTS pqms//
CREATE TABLE pqms (
  id int(11) NOT NULL,
  user_id int(11) DEFAULT NULL,
  county_id int(11) DEFAULT NULL,
  sub_county_id int(11) DEFAULT NULL,
  country_id int(11) DEFAULT NULL,
  designation_id int(11) DEFAULT NULL,
  facility_name varchar(100) DEFAULT NULL,
  facility_code varchar(100) DEFAULT NULL,
  facility_address varchar(100) DEFAULT NULL,
  facility_phone varchar(100) DEFAULT NULL,
  brand_name varchar(100) DEFAULT NULL,
  generic_name varchar(100) DEFAULT NULL,
  batch_number varchar(100) DEFAULT NULL,
  manufacture_date varchar(20) DEFAULT NULL,
  expiry_date date DEFAULT NULL,
  receipt_date date DEFAULT NULL,
  name_of_manufacturer varchar(100) DEFAULT NULL,
  country_of_origin varchar(100) DEFAULT NULL,
  supplier_name varchar(100) DEFAULT NULL,
  supplier_address varchar(100) DEFAULT NULL,
  product_formulation varchar(70) DEFAULT NULL,
  product_formulation_specify varchar(250) DEFAULT NULL,
  colour_change tinyint(1) DEFAULT NULL,
  separating tinyint(1) DEFAULT NULL,
  powdering tinyint(1) DEFAULT NULL,
  caking tinyint(1) DEFAULT NULL,
  moulding tinyint(1) DEFAULT NULL,
  odour_change tinyint(1) DEFAULT NULL,
  mislabeling tinyint(1) DEFAULT NULL,
  incomplete_pack tinyint(1) DEFAULT NULL,
  complaint_other tinyint(1) DEFAULT NULL,
  complaint_other_specify text,
  complaint_description text,
  require_refrigeration varchar(10) DEFAULT NULL,
  product_at_facility varchar(10) DEFAULT NULL,
  returned_by_client varchar(10) DEFAULT NULL,
  stored_to_recommendations varchar(10) DEFAULT NULL,
  other_details text,
  comments text,
  reporter_name varchar(100) DEFAULT NULL,
  reporter_email varchar(100) DEFAULT NULL,
  contact_number varchar(100) DEFAULT NULL,
  emails tinyint(2) DEFAULT '0',
  submitted tinyint(2) DEFAULT '0',
  active tinyint(1) DEFAULT '1',
  device tinyint(2) DEFAULT '0',
  notified tinyint(2) DEFAULT '0',
  created datetime DEFAULT NULL,
  modified datetime DEFAULT NULL,
  ppid bigint(11) DEFAULT NULL,
  synch int(11) NOT NULL DEFAULT '0'
)//