update sync_facility set dhiscode = 'aB8dffITO0K'where id =	1212 //
update sync_facility set dhiscode = 'aGjc4COyBBG'where id =	2373 //
update sync_facility set dhiscode = 'aL5ylUzJokH'where id =	1322 //
update sync_facility set dhiscode = 'AOpLUrJHaZ0'where id =	1389 //
update sync_facility set dhiscode = 'b90hWLhlW5P'where id =	986 //
update sync_facility set dhiscode = 'b9PRSKsPyq0'where id =	1871 //
update sync_facility set dhiscode = 'ba63sP0ArOy'where id =	2183 //
update sync_facility set dhiscode = 'bDWpyLyczKC'where id =	1342 //
update sync_facility set dhiscode = 'BEhwuNM8KZa'where id =	1172 //
update sync_facility set dhiscode = 'bfDG89DkYI8'where id =	1568 //
update sync_facility set dhiscode = 'bGJEeoqpsS0'where id =	1571 //
update sync_facility set dhiscode = 'bKxYPaUCLWz'where id =	2175 //
update sync_facility set dhiscode = 'bnQePNfUZB8'where id =	1739 //
update sync_facility set dhiscode = 'BTkvpaSEq55'where id =	1737 //
update sync_facility set dhiscode = 'C90xbsP52u7'where id =	1134 //
update sync_facility set dhiscode = 'c93Xc1VYJfv'where id =	1332 //
update sync_facility set dhiscode = 'CFOmFTRmpEp'where id =	1824 //
update sync_facility set dhiscode = 'cg8vrDBJqrQ'where id =	2356 //
update sync_facility set dhiscode = 'cgGKqOQ5YLB'where id =	1783 //
update sync_facility set dhiscode = 'Cn1jEGMmoIF'where id =	2150 //
update sync_facility set dhiscode = 'CuGI0PdC46e'where id =	1534 //
update sync_facility set dhiscode = 'cW5YDD9s3fq'where id =	2223 //
update sync_facility set dhiscode = 'D1sJppq7GNI'where id =	621 //
update sync_facility set dhiscode = 'D42FRdqN4Jy'where id =	1075 //
update sync_facility set dhiscode = 'D4fYExYuVJ5'where id =	2231 //
update sync_facility set dhiscode = 'D4m9AGzcm6E'where id =	1113 //
update sync_facility set dhiscode = 'D68YtIg7snb'where id =	1715 //
update sync_facility set dhiscode = 'd69tynUHL9A'where id =	1455 //
update sync_facility set dhiscode = 'd6uWTkItX35'where id =	336 //
update sync_facility set dhiscode = 'dFc5sVNIz0Q'where id =	1358 //
update sync_facility set dhiscode = 'diQrdijS870'where id =	1474 //
update sync_facility set dhiscode = 'DNnvCXUMH4v'where id =	975 //
update sync_facility set dhiscode = 'dVJIr4Sy7na'where id =	1623 //
update sync_facility set dhiscode = 'dW7oScLnDy2'where id =	1015 //
update sync_facility set dhiscode = 'EddKiEXCXSD'where id =	943 //
update sync_facility set dhiscode = 'edjfwbsoTLn'where id =	1265 //
update sync_facility set dhiscode = 'efB1pCkQL0b'where id =	1724 //
update sync_facility set dhiscode = 'EGLsWYmCYGh'where id =	1425 //
update sync_facility set dhiscode = 'EGS0saGNDoS'where id =	2153 //
update sync_facility set dhiscode = 'eK8QlnL4wIZ'where id =	1754 //
update sync_facility set dhiscode = 'EkaphfjRPxs'where id =	608 //
update sync_facility set dhiscode = 'enFogPQF7aZ'where id =	2018 //
update sync_facility set dhiscode = 'EzccfHE7VSe'where id =	2066 //
update sync_facility set dhiscode = 'f3XukP1v8uT'where id =	1041 //
update sync_facility set dhiscode = 'Fc0JkHQA1og'where id =	1766 //
update sync_facility set dhiscode = 'fcJSDP22rHp'where id =	1234 //
update sync_facility set dhiscode = 'fHrucmAW82q'where id =	1254 //
update sync_facility set dhiscode = 'FJLwPzKpxiy'where id =	1903 //
update sync_facility set dhiscode = 'fjWbG8ESObj'where id =	1375 //
update sync_facility set dhiscode = 'FKg6dfWiMHX'where id =	2114 //
update sync_facility set dhiscode = 'fMMxisqLyA8'where id =	1878 //
update sync_facility set dhiscode = 'FN564hpaXtv'where id =	1624 //
update sync_facility set dhiscode = 'fNFnpjIy5Li'where id =	805 //
update sync_facility set dhiscode = 'fr2WuyAuQPz'where id =	987 //
update sync_facility set dhiscode = 'fvnBMGJT2Sb'where id =	253 //
update sync_facility set dhiscode = 'g2hI4r6dWLi'where id =	1372 //
update sync_facility set dhiscode = 'g6jjdlzh7ju'where id =	1512 //
update sync_facility set dhiscode = 'gaWE49ZEO47'where id =	1163 //
update sync_facility set dhiscode = 'gCRidS1x9ty'where id =	167 //
update sync_facility set dhiscode = 'Gk01HeIfjsg'where id =	1777 //
update sync_facility set dhiscode = 'GK7ahcXkU36'where id =	657 //
update sync_facility set dhiscode = 'GWyiedUwAyx'where id =	1702 //
update sync_facility set dhiscode = 'gZQwily9jnU'where id =	2140 //
update sync_facility set dhiscode = 'h0Iego3IFFN'where id =	1731 //
update sync_facility set dhiscode = 'hcpENHJ3wEq'where id =	1346 //
update sync_facility set dhiscode = 'HdMCcz0HfIP'where id =	1597 //
update sync_facility set dhiscode = 'hg4o1hnnpvV'where id =	2274 //
update sync_facility set dhiscode = 'HG5fUsbdzk6'where id =	1027 //
update sync_facility set dhiscode = 'hnveIA9HE5L'where id =	1893 //
update sync_facility set dhiscode = 'hqPkw34FUAM'where id =	827 //
update sync_facility set dhiscode = 'hsf8JIi1GSI'where id =	2195 //
update sync_facility set dhiscode = 'Ig4nN4ZgawG'where id =	1518 //
update sync_facility set dhiscode = 'iQqQPaktVMP'where id =	467 //
update sync_facility set dhiscode = 'iSWYUchYnlP'where id =	1441 //
update sync_facility set dhiscode = 'j0iEelzUyJn'where id =	1496 //
update sync_facility set dhiscode = 'J2nSU1CrG7s'where id =	1272 //
update sync_facility set dhiscode = 'j4ykbP2YFIw'where id =	1351 //
update sync_facility set dhiscode = 'JjIbDDg4pZ6'where id =	2101 //
update sync_facility set dhiscode = 'jLqcqbQu3bq'where id =	1392 //
update sync_facility set dhiscode = 'Ju1VTrrdBjr'where id =	1473 //
update sync_facility set dhiscode = 'jyOyZUU0qJT'where id =	1936 //
update sync_facility set dhiscode = 'jzQPk6CszMu'where id =	1435 //
update sync_facility set dhiscode = 'k5DoW10XF8Q'where id =	1105 //
update sync_facility set dhiscode = 'k6tMRaA8sOX'where id =	1682 //
update sync_facility set dhiscode = 'k9s6Zi8KAVw'where id =	1262 //
update sync_facility set dhiscode = 'kH3yXjFQi6C'where id =	2346 //
update sync_facility set dhiscode = 'kIkn9YIz4Qj'where id =	2264 //
update sync_facility set dhiscode = 'ktDX2G1jcfH'where id =	1286 //
update sync_facility set dhiscode = 'KXdhriS958s'where id =	1538 //
update sync_facility set dhiscode = 'lDKXWFaCEa1'where id =	601 //
update sync_facility set dhiscode = 'LE41inNgUSw'where id =	1650 //
update sync_facility set dhiscode = 'LeiEBPdQtoW'where id =	489 //
update sync_facility set dhiscode = 'LPKh4nXw3jE'where id =	1014 //
update sync_facility set dhiscode = 'LSjjW2Uph1L'where id =	2124 //
update sync_facility set dhiscode = 'lSqQNspMLuC'where id =	1462 //
update sync_facility set dhiscode = 'LWoO0Z47tGZ'where id =	762 //
update sync_facility set dhiscode = 'lzOUpzvVUbj'where id =	1857 //
update sync_facility set dhiscode = 'm6zhE2pzHWO'where id =	1968 //
update sync_facility set dhiscode = 'm7UbpJjPOIj'where id =	1479 //
update sync_facility set dhiscode = 'mC4qkTGiah3'where id =	265 //
update sync_facility set dhiscode = 'mFCdD8GzFQC'where id =	1018 //
update sync_facility set dhiscode = 'Mh62QGkagBb'where id =	1991 //
update sync_facility set dhiscode = 'Mr5ai8GXGEj'where id =	1494 //
update sync_facility set dhiscode = 'mRyzf0z5qM9'where id =	1536 //
update sync_facility set dhiscode = 'MWcwkURjOjR'where id =	2347 //
update sync_facility set dhiscode = 'mYYRg95WnP1'where id =	1701 //
update sync_facility set dhiscode = 'N1esU27uHON'where id =	1403 //
update sync_facility set dhiscode = 'N5zFU9qwwa6'where id =	1489 //
update sync_facility set dhiscode = 'N6JAq2xtuW7'where id =	1269 //
update sync_facility set dhiscode = 'N77UkGoiY0M'where id =	1992 //
update sync_facility set dhiscode = 'nbOitoazhsA'where id =	1090 //
update sync_facility set dhiscode = 'NkqrwaJrPZy'where id =	1484 //
update sync_facility set dhiscode = 'Nm7pDZgl88V'where id =	1642 //
update sync_facility set dhiscode = 'noXSekQKwA1'where id =	1523 //
update sync_facility set dhiscode = 'nTGZm5lNyzY'where id =	1889 //
update sync_facility set dhiscode = 'nUrZ9LlaEsm'where id =	1279 //
update sync_facility set dhiscode = 'NVma9uFYL5X'where id =	1200 //
update sync_facility set dhiscode = 'nw9YVA9Tx6R'where id =	1784 //
update sync_facility set dhiscode = 'oBjfZoeDfgn'where id =	1607 //
update sync_facility set dhiscode = 'oic5beVUm72'where id =	1988 //
update sync_facility set dhiscode = 'OjfMUlTYbK1'where id =	2182 //
update sync_facility set dhiscode = 'OOwfPj8lwtK'where id =	2132 //
update sync_facility set dhiscode = 'OTu4xNrbdX0'where id =	835 //
update sync_facility set dhiscode = 'oveetILWJK3'where id =	2116 //
update sync_facility set dhiscode = 'OvL7GM8rL9p'where id =	1847 //
update sync_facility set dhiscode = 'Oxj36jLUDn8'where id =	1541 //
update sync_facility set dhiscode = 'pC90awhA0Xv'where id =	1498 //
update sync_facility set dhiscode = 'PHJHqpSpfRc'where id =	1895 //
update sync_facility set dhiscode = 'PMaCD9epy9o'where id =	1770 //
update sync_facility set dhiscode = 'pOzVvOXQ6TL'where id =	2310 //
update sync_facility set dhiscode = 'pS72TtLnCvM'where id =	457 //
update sync_facility set dhiscode = 'pyVe7DfRPnj'where id =	2302 //
update sync_facility set dhiscode = 'q7a1TH1APLe'where id =	2154 //
update sync_facility set dhiscode = 'QPi8HppUeQL'where id =	1904 //
update sync_facility set dhiscode = 'QtkuzgCwZnB'where id =	600 //
update sync_facility set dhiscode = 'qwkeGWo4AG6'where id =	1118 //
update sync_facility set dhiscode = 'Qwv7vHBFvMl'where id =	2345 //
update sync_facility set dhiscode = 'R41QQ3YpoYu'where id =	2367 //
update sync_facility set dhiscode = 'Rb2ToilrNJu'where id =	864 //
update sync_facility set dhiscode = 'rRqKxDRl7GI'where id =	1922 //
update sync_facility set dhiscode = 'rsvp3dkcgmQ'where id =	723 //
update sync_facility set dhiscode = 'RTZe6hZlVEc'where id =	755 //
update sync_facility set dhiscode = 'RvfuTKWH9qj'where id =	1847 //
update sync_facility set dhiscode = 'RYu0mIssWOk'where id =	1727 //
update sync_facility set dhiscode = 'S6QG3RQBMma'where id =	1394 //
update sync_facility set dhiscode = 'SC3NnIGa5u0'where id =	1113 //
update sync_facility set dhiscode = 'SFjHKmBnUQl'where id =	1618 //
update sync_facility set dhiscode = 'sIkxI1RwQvs'where id =	1524 //
update sync_facility set dhiscode = 'sJHMc412zV6'where id =	1008 //
update sync_facility set dhiscode = 'SjnJ45W6QQO'where id =	1128 //
update sync_facility set dhiscode = 'SPfT81d1gVx'where id =	1013 //
update sync_facility set dhiscode = 'SuxAmnVfsiA'where id =	487 //
update sync_facility set dhiscode = 'sVieRplg6f3'where id =	1301 //
update sync_facility set dhiscode = 'T8ykBEN4kyI'where id =	1892 //
update sync_facility set dhiscode = 'TaFv14A2EPb'where id =	1098 //
update sync_facility set dhiscode = 'tdskla3Fuag'where id =	647 //
update sync_facility set dhiscode = 'tGjtjysHEUY'where id =	1391 //
update sync_facility set dhiscode = 'ThMZDEYrucq'where id =	1576 //
update sync_facility set dhiscode = 'TJ1XC7INTvl'where id =	1283 //
update sync_facility set dhiscode = 'tlcvZ4jzPwM'where id =	1945 //
update sync_facility set dhiscode = 'tNpT77xOcjl'where id =	1183 //
update sync_facility set dhiscode = 'toXjP0GCaAw'where id =	1563 //
update sync_facility set dhiscode = 'tww0l46CGoh'where id =	2305 //
update sync_facility set dhiscode = 'tYtTS1NxbBe'where id =	1088 //
update sync_facility set dhiscode = 'u0gDQ38iF5S'where id =	381 //
update sync_facility set dhiscode = 'u2QWwuSUzy8'where id =	1094 //
update sync_facility set dhiscode = 'u6txfT5EKDc'where id =	308 //
update sync_facility set dhiscode = 'uBauAUNClfm'where id =	1218 //
update sync_facility set dhiscode = 'uMdDAxe9poY'where id =	1507 //
update sync_facility set dhiscode = 'uutSAJMeA3s'where id =	1010 //
update sync_facility set dhiscode = 'VCIQiK1o2aS'where id =	1390 //
update sync_facility set dhiscode = 'veSlX1emBbZ'where id =	1490 //
update sync_facility set dhiscode = 'vIWWNctiwz1'where id =	1168 //
update sync_facility set dhiscode = 'VMkinArVTDQ'where id =	1108 //
update sync_facility set dhiscode = 'VzKk9IOkE2W'where id =	895 //
update sync_facility set dhiscode = 'w3vPowuxUH1'where id =	1589 //
update sync_facility set dhiscode = 'w5udNAfZvrb'where id =	929 //
update sync_facility set dhiscode = 'WCjUg04KkUY'where id =	2067 //
update sync_facility set dhiscode = 'WdXqR4s4oYz'where id =	1034 //
update sync_facility set dhiscode = 'WjEssqA66dw'where id =	1935 //
update sync_facility set dhiscode = 'WPhMyqa7tMP'where id =	1007 //
update sync_facility set dhiscode = 'wPsUQXK6ynT'where id =	2158 //
update sync_facility set dhiscode = 'XpgCObK6h8l'where id =	2327 //
update sync_facility set dhiscode = 'xuVsQTby6uM'where id =	1438 //
update sync_facility set dhiscode = 'XZwiXe6lGnE'where id =	1837 //
update sync_facility set dhiscode = 'Y2bOKooRPaH'where id =	1134 //
update sync_facility set dhiscode = 'Y9qucizTmZG'where id =	2149 //
update sync_facility set dhiscode = 'YejIqzsdjR2'where id =	1233 //
update sync_facility set dhiscode = 'Ymc9IW5Tzgh'where id =	1252 //
update sync_facility set dhiscode = 'YtsM0MqcxLu'where id =	2166 //
update sync_facility set dhiscode = 'YymiTkFWN6F'where id =	1429 //
update sync_facility set dhiscode = 'zcimVankk22'where id =	1096 //
update sync_facility set dhiscode = 'zDGztuhkhx7'where id =	1890 //
update sync_facility set dhiscode = 'zFZsmfHjSQM'where id =	1630 //
update sync_facility set dhiscode = 'zglOjJmJNAI'where id =	2274 //
update sync_facility set dhiscode = 'Zl8JMj5NOHk'where id =	2012 //
update sync_facility set dhiscode = 'zvWQ5tdZfKO'where id =	398 //
update sync_facility set dhiscode = 'ZZRbej4f3XS'where id =	2104 //
update sync_facility set dhiscode = 'AawtXdUefwb'where id =	7 //
update sync_facility set dhiscode = 'ilDri0Q6GWc'where id =	365 //
update sync_facility set dhiscode = 'qk1UIwzC9zv'where id =	2407 //
update sync_facility set dhiscode = 'mC9U2woN9J3'where id =	1791 //
update sync_facility set dhiscode = 'Epg5CqAuaHn'where id =	77 //
update sync_facility set dhiscode = 'NGH1by3UZpG'where id =	2146 //
update sync_facility set dhiscode = 't7uvA9RZl3d'where id =	2131 //
update sync_facility set dhiscode = 'PSEIjVWiDf1'where id =	2164 //
update sync_facility set dhiscode = 'EMo5Bjqn9SI'where id =	2213 //
update sync_facility set dhiscode = 'YVbnjQr0hoD'where id =	2340 //
update sync_facility set dhiscode = 'QicfgXP0eIq'where id =	370 //
update sync_facility set dhiscode = 'E7liN0388Dd'where id =	303 //
update sync_facility set dhiscode = 'iXe82pbM0g6'where id =	219 //